module Emojistatic
  # Clean up the manifest generated by manifesto to add a static prefix to URIs
  def self.prefix_manifest(manifest, prefix)
    manifest.gsub!(
      /^\//,
      "#{prefix}/"
    )
    manifest.gsub!(
      "Generated by manifesto (http://github.com/johntopley/manifesto)",
      "Generated by manifesto (http://github.com/johntopley/manifesto)\n# Modified by emojistatic (http://github.com/mroth/emojistatic)"
    )
  end
end